[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.dagster]
modules = [
    { type = "module", name = "binge_works" },
    { type = "module", name = "fantasy_navigator" },
]
